const data = [
    {
      taskId: 1,
      task: 'Client Kick Off / SOW Signed / Campaign Matrix Approved',
      duration: 1,
      startDate: new Date('2024-05-22'),
      finishDate: null,
      comments: null,
      status: null,
      assignedTo: null,
      priorTo: null,
      alignedBy: null,
    },
    {
      taskId: 2,
      task: 'Internal Creative Kick Off',
      duration: 1,
      startDate: null,
      finishDate: null,
      comments: null,
      status: null,
      assignedTo: null,
      priorTo: null,
      alignedBy: null,
    },
    {
      taskId: 3,
      task: 'Creative Concept development',
      duration: 1,
      startDate: null,
      finishDate: null,
      comments: null,
      status: null,
      assignedTo: null,
      priorTo: null,
      alignedBy: null,
    },
    {
      taskId: 4,
      task: 'Internal Review Concept',
      duration: 1,
      startDate: null,
      finishDate: null,
      comments: null,
      status: null,
      assignedTo: null,
      priorTo: null,
      alignedBy: null,
    },
    {
      taskId: 5,
      task: 'Present Concept(s) to Client / Client Gives Feedback',
      duration: 1,
      startDate: null,
      finishDate: null,
      comments: null,
      status: null,
      assignedTo: null,
      priorTo: null,
      alignedBy: null,
    },
    {
      taskId: 6,
      task: 'Creative Development',
      duration: 1,
      startDate: null,
      finishDate: null,
      comments: null,
      status: null,
      assignedTo: null,
      priorTo: null,
      alignedBy: null,
    },
    {
      taskId: 7,
      task: 'Internal Review/Alterations',
      duration: 1,
      startDate: null,
      finishDate: null,
      comments: null,
      status: null,
      assignedTo: null,
      priorTo: null,
      alignedBy: null,
    },
    {
      taskId: 8,
      task: 'Fully Executed Creative Presented to Client',
      duration: 1,
      startDate: null,
      finishDate: null,
      comments: null,
      status: null,
      assignedTo: null,
      priorTo: null,
      alignedBy: null,
    },
    {
      taskId: 9,
      task: 'Client reviews creative - Round 1',
      duration: 1,
      startDate: null,
      finishDate: null,
      comments: null,
      status: null,
      assignedTo: null,
      priorTo: null,
      alignedBy: null,
    },
    {
      taskId: 10,
      task: 'SeQuel adjusts creative - sends pdfs',
      duration: 1,
      startDate: null,
      finishDate: null,
      comments: null,
      status: null,
      assignedTo: null,
      priorTo: null,
      alignedBy: null,
    },
    {
      taskId: 11,
      task: 'Client reviews - Round 2',
      duration: 1,
      startDate: null,
      finishDate: null,
      comments: null,
      status: null,
      assignedTo: null,
      priorTo: null,
      alignedBy: null,
    },
    {
      taskId: 12,
      task: 'Envelope art approval - release to production',
      duration: 1,
      startDate: null,
      finishDate: null,
      comments: null,
      status: null,
      assignedTo: null,
      priorTo: null,
      alignedBy: null,
    },
    {
      taskId: 13,
      task: 'SeQuel adjusts - sends pdfs',
      duration: 1,
      startDate: null,
      finishDate: null,
      comments: null,
      status: null,
      assignedTo: null,
      priorTo: null,
      alignedBy: null,
    },
    {
      taskId: 14,
      task: 'Client reviews - Final approval',
      duration: 1,
      startDate: null,
      finishDate: null,
      comments: null,
      status: null,
      assignedTo: null,
      priorTo: null,
      alignedBy: null,
    },
    {
      taskId: 15,
      task: 'Generate Informed Delivery Ads - Release to production',
      duration: 1,
      startDate: null,
      finishDate: null,
      comments: null,
      status: null,
      assignedTo: null,
      priorTo: null,
      alignedBy: null,
    },
    {
      taskId: 16,
      task: 'Preflight - Release to Production (before noon)',
      duration: 1,
      startDate: null,
      finishDate: null,
      comments: null,
      status: null,
      assignedTo: null,
      priorTo: null,
      alignedBy: null,
    },
    {
      taskId: 17,
      task: 'Customer file for modeling/Suppression file/Leads/DNC/State Omits due to SeQuel',
      duration: 1,
      startDate: null,
      finishDate: null,
      comments: null,
      status: null,
      assignedTo: null,
      priorTo: null,
      alignedBy: null,
    },
    {
      taskId: 18,
      task: 'Data Management',
      duration: 1,
      startDate: null,
      finishDate: null,
      comments: null,
      status: null,
      assignedTo: null,
      priorTo: null,
      alignedBy: null,
    },
    {
      taskId: 19,
      task: 'Data Due to Production (before noon)',
      duration: 1,
      startDate: null,
      finishDate: null,
      comments: null,
      status: null,
      assignedTo: null,
      priorTo: null,
      alignedBy: null,
    },
    {
      taskId: 20,
      task: 'Postage Invoice Due to Client',
      duration: 1,
      startDate: null,
      finishDate: null,
      comments: null,
      status: null,
      assignedTo: null,
      priorTo: null,
      alignedBy: null,
    },
    {
      taskId: 21,
      task: 'Postage Due to SeQuel',
      duration: 1,
      startDate: null,
      finishDate: null,
      comments: null,
      status: null,
      assignedTo: null,
      priorTo: null,
      alignedBy: null,
    },
    {
      taskId: 22,
      task: 'Print production',
      duration: 1,
      startDate: null,
      finishDate: null,
      comments: null,
      status: null,
      assignedTo: null,
      priorTo: null,
      alignedBy: null,
    },
    {
      taskId: 23,
      task: 'In Home Window',
      duration: 1,
      startDate: null,
      finishDate: null,
      comments: null,
      status: null,
      assignedTo: null,
      priorTo: null,
      alignedBy: null,
    },
    {
      taskId: 24,
      task: 'Send samples',
      duration: 1,
      startDate: null,
      finishDate: null,
      comments: null,
      status: null,
      assignedTo: null,
      priorTo: null,
      alignedBy: null,
    },
    {
      taskId: 25,
      task: 'Initiate invoicing - Send final invoice',
      duration: 1,
      startDate: null,
      finishDate: null,
      comments: null,
      status: null,
      assignedTo: null,
      priorTo: null,
      alignedBy: null,
    },
  ];
  